# Generated by Django 3.0.6 on 2020-05-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, upload_to='people/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('order', models.IntegerField(verbose_name='Номер отображения')),
                ('vk', models.CharField(blank=True, default='-', max_length=100, verbose_name='VK')),
                ('inst', models.CharField(blank=True, default='-', max_length=100, verbose_name='Inst')),
            ],
            options={
                'verbose_name': 'Люди',
            },
        ),
    ]
