# Generated by Django 3.0.6 on 2020-05-29 00:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fontans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=140, verbose_name='Описание')),
                ('color', models.CharField(blank=True, default='red', max_length=100, verbose_name='color')),
                ('link', models.URLField(verbose_name='URL')),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='содержание')),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='df2020/people', verbose_name='Фото')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='описание или инструкция')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('order', models.IntegerField(default=0, verbose_name='Номер отображения')),
            ],
            options={
                'verbose_name': 'Человек или конкурс',
                'verbose_name_plural': 'Человеки или конкрусы',
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140, verbose_name='содержание')),
                ('color', models.CharField(blank=True, default='red', max_length=100, verbose_name='color')),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Стикер',
                'verbose_name_plural': 'Стикеры',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='df2020/sections/', verbose_name='Обложка')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='описание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('order', models.IntegerField(default=0, verbose_name='Номер отображения')),
                ('people', models.ManyToManyField(blank=True, to='df2020.People')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image_preview', models.ImageField(blank=True, upload_to='df2020/', verbose_name='Обложка на странице дф2020')),
                ('image', models.ImageField(blank=True, upload_to='df2020/page/', verbose_name='Обложка на основной странице')),
                ('small_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='описание')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на перенаправление')),
                ('order', models.IntegerField(default=0, verbose_name='Номер отображения')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.Gallery', verbose_name='Галерея')),
                ('sections', models.ManyToManyField(blank=True, to='df2020.Sections')),
            ],
            options={
                'verbose_name': 'Старнциа',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
